import { isSensorFormatId } from './formats.ts'
import type { CocCriterion, SensorFormatId } from './formats.ts'
import { clampToLens, getLens } from './lenses.ts'

export interface OpticsParams {
  readonly lensId: string
  readonly focalLengthMm: number
  readonly fNumber: number
  readonly focusDistanceM: number
  readonly sensorId: SensorFormatId
  readonly cocCriterion: CocCriterion
  readonly diffraction: boolean
}

export const DEFAULT_OPTICS: OpticsParams = {
  lensId: 'ef-50-1p4',
  focalLengthMm: 50,
  fNumber: 1.4,
  focusDistanceM: 4,
  sensorId: 'ff',
  cocCriterion: { kind: 'formatConvention' },
  diffraction: true,
}

// ---------------------------------------------------------------------------
// Coercion helpers. Everything arriving from a URL is a string, and a URL can
// be hand-edited, truncated, or generated by an older version of this app.
// ---------------------------------------------------------------------------

function asRecord(raw: unknown): Record<string, unknown> {
  return typeof raw === 'object' && raw !== null && !Array.isArray(raw)
    ? (raw as Record<string, unknown>)
    : {}
}

function num(v: unknown): number | undefined {
  if (typeof v === 'number') return Number.isFinite(v) ? v : undefined
  if (typeof v === 'string' && v.trim() !== '') {
    const n = Number(v)
    return Number.isFinite(n) ? n : undefined
  }
  return undefined
}

function bool(v: unknown, fallback: boolean): boolean {
  if (typeof v === 'boolean') return v
  if (typeof v === 'number') return v !== 0
  if (typeof v === 'string') {
    if (/^(true|1|yes|on)$/i.test(v)) return true
    if (/^(false|0|no|off)$/i.test(v)) return false
  }
  return fallback
}

const CONVENTION: CocCriterion = { kind: 'formatConvention' }

export function encodeCocCriterion(c: CocCriterion): string {
  switch (c.kind) {
    case 'formatConvention':
      return 'convention'
    case 'diagonalDivisor':
      return `div:${c.divisor}`
    case 'absoluteMm':
      return `mm:${c.mm}`
    case 'renderPixels':
      return `px:${c.px}`
  }
}

export function decodeCocCriterion(raw: unknown): CocCriterion {
  // Accept the object form too, so a normalized value can be re-normalized.
  if (typeof raw === 'object' && raw !== null && 'kind' in raw) {
    const o = raw as { kind: unknown; divisor?: unknown; mm?: unknown; px?: unknown }
    switch (o.kind) {
      case 'formatConvention':
        return CONVENTION
      case 'diagonalDivisor': {
        const d = num(o.divisor)
        return d !== undefined && d > 0 ? { kind: 'diagonalDivisor', divisor: d } : CONVENTION
      }
      case 'absoluteMm': {
        const mm = num(o.mm)
        return mm !== undefined && mm > 0 ? { kind: 'absoluteMm', mm } : CONVENTION
      }
      case 'renderPixels': {
        const px = num(o.px)
        return px !== undefined && px > 0 ? { kind: 'renderPixels', px } : CONVENTION
      }
      default:
        return CONVENTION
    }
  }

  if (typeof raw !== 'string') return CONVENTION
  if (raw === 'convention') return CONVENTION
  const [prefix, rest] = raw.split(':', 2)
  const v = num(rest)
  if (v === undefined || !(v > 0)) return CONVENTION
  switch (prefix) {
    case 'div':
      return { kind: 'diagonalDivisor', divisor: v }
    case 'mm':
      return { kind: 'absoluteMm', mm: v }
    case 'px':
      return { kind: 'renderPixels', px: v }
    default:
      return CONVENTION
  }
}

/**
 * Total function: for ANY input it returns usable parameters. It never throws
 * and never yields NaN.
 *
 * This is deliberate rather than defensive. These values come from the URL, so
 * a stale or hand-mangled link should degrade to something sensible instead of
 * tripping an error boundary. The clamping here is domain logic -- an f-number
 * has to be one the chosen lens can actually reach at the chosen focal length
 * -- which is why this is hand-written rather than a schema.
 */
export function normalizeOpticsParams(raw: unknown): OpticsParams {
  const r = asRecord(raw)

  // Long names are the in-app shape; short names are the URL shape.
  const pick = (long: string, short: string): unknown => r[long] ?? r[short]

  const lensIdRaw = pick('lensId', 'lens')
  const lens =
    (typeof lensIdRaw === 'string' ? getLens(lensIdRaw) : undefined) ??
    getLens(DEFAULT_OPTICS.lensId)!

  const sensorIdRaw = pick('sensorId', 'sensor')
  const sensorId = isSensorFormatId(sensorIdRaw) ? sensorIdRaw : DEFAULT_OPTICS.sensorId

  const requestedFocal = num(pick('focalLengthMm', 'f'))
  const requestedF = num(pick('fNumber', 'N'))
  const requestedFocus = num(pick('focusDistanceM', 's'))

  const bound = clampToLens(lens, {
    // Falling back to the lens's own wide end keeps a lens switch predictable.
    focalLengthMm: requestedFocal ?? lens.focalRangeMm[0],
    fNumber: requestedF ?? lens.maxApertureWide,
    focusDistanceM:
      requestedFocus !== undefined && requestedFocus > 0
        ? requestedFocus
        : DEFAULT_OPTICS.focusDistanceM,
  })

  return {
    lensId: lens.id,
    ...bound,
    sensorId,
    cocCriterion: decodeCocCriterion(pick('cocCriterion', 'coc')),
    diffraction: bool(pick('diffraction', 'diff'), DEFAULT_OPTICS.diffraction),
  }
}

export function encodeOpticsParams(p: OpticsParams): Record<string, string | number> {
  return {
    lens: p.lensId,
    f: p.focalLengthMm,
    N: p.fNumber,
    s: p.focusDistanceM,
    sensor: p.sensorId,
    coc: encodeCocCriterion(p.cocCriterion),
    diff: p.diffraction ? 1 : 0,
  }
}
